### ISSUE TITLE
Error in OidcJwtHelper

### ISSUE THREAD

**Issue by avitacco** [Drenso/symfony-oidc#11]
During my authentication phase, I am getting an error from `OidcJwtHelper`.

```
Drenso\OidcBundle\OidcJwtHelper::decodeJwt(): Return value must be of type object, null returned
```

I did some debugging and it looks like the value that is being returned to `decodeJwt` from the `base64url_decode` function when `$section` is `0` is binary so when `json_decode` is called it fails and returns a null. I am not familiar enough with OIDC to be able to say why the value is binary or what the normal expected value is.

I would be happy to post the encoded value here, but I'm not sure if it contains any secrets.

**Comment by bobvandevijver** [comment]
Can you check the values of the two tokens (access token and id token) in the tokens object?

![image](https://user-images.githubusercontent.com/1835343/146271268-064dee40-3cec-4f2c-816e-f372d93b1350.png)

You should **never** post full tokens anywhere, as they can grant access to resources. However, you can use https://jwt.io/ to see what's in there. The contents should never be binary though: JWT token are not much more than three base64 encoded pieces of json encoded data (so, strings), which you can see on the linked site as well. The first part is the header containing information about the token and how it is signed (which is actually safe to post), followed by the data being transferred and the last part is the signature which can be validated to see whether the token is actually valid. The parts are separated by a dot.

As example, this is an access token I just retrieved and pasted in the jwt.io tool:

![image](https://user-images.githubusercontent.com/1835343/146272425-fab2dcfa-5f1d-4a9d-b6ac-cf3f0c1b45e7.png)

So the question here is: why is your token header malformed?

By the way, https://jwt.io/introduction has a nice introduction about how JWTs work if you're interested.

**Comment by avitacco** [comment]
I have been working to narrow down the cause of this issue. It turns out that the access token I'm being given is not a valid JWT. I contacted the team who run our idp and they say everything seems to be working correctly on their end.

I raised the issues I'm having with them saying that the access token does not correctly and is therefore malformed. Their response is that the vendor for the product we use has implemented the access token as a basic string and is not, in fact a JWT. This is done this way because the OAuth2 spec does not define the format for the access token meaning that it can be a string in any format. Commonly JWT is used, but our vendor in this case has opted not to use JWT for their access tokens.

See also https://github.com/CSCfi/shibboleth-idp-oidc-extension/issues/22

I should add just for completeness here that `jumbojett/openid-connect-php` works 100% correctly on the exact same endpoints.

The question is, given that it is possible for access tokens not to be JWT is it sensible to check to see if they are before attempting to treat them as such?

**Comment by bobvandevijver** [comment]
You are right, the OIDC specification indeed does not force the access token to be a JWT and as we recently added strict return typings to the `decodeJWT` method it now fails, while that is not the case for the `jumbojett` implementation as that misses those strict return types.

Which branch are you using? The v2 I right? Once confirmed, I will see if I can update the implementation to allow non-JWT access tokens.

**Comment by avitacco** [comment]
That is correct, I am using v2 on Symfony 6/PHP 8.0.

**Comment by bobvandevijver** [comment]
@avitacco Can you check whether the `11-non-jwt-access-token` fixes the problem for you? You can install it with `composer req drenso/symfony-oidc-bundle:dev-11-non-jwt-access-token`

**Comment by avitacco** [comment]
@bobvandevijver That fixes the error. I have a redirect loop now, but that could very well be a problem with my code.

```php
class AuthenticationController extends AbstractController
{
    /**
     * @param SessionInterface $session
     * @param OidcClientInterface $oidcClient
     * @return RedirectResponse
     * @throws OidcConfigurationException
     * @throws OidcConfigurationResolveException
     */
    #[Route('/login', name: 'login')]
    #[IsGranted('PUBLIC_ACCESS')]
    public function login(
        SessionInterface $session,
        OidcClientInterface $oidcClient,
    ): RedirectResponse {
        return $oidcClient->generateAuthorizationRedirect(
            scopes: ['openid', 'profile', 'email']
        );
    }

    #[Route('/login_check', name: 'login_check')]
    #[IsGranted('PUBLIC_ACCESS')]
    public function loginCheck()
    {
        return $this->redirectToRoute('download_page');
    }
}
```

**Comment by bobvandevijver** [comment]
You should no longer need the explicit login check route (or at least, not for this bundle in its default configuration).

For the redirect loop, you should check whether the user provider works for you (including refresh). The Symfony logs might tell you why the user session won't stick.

**Comment by avitacco** [comment]
Without the login_check route I get a routing error when the idp redirects back to the site.

Here are my log entries from the login attempt:
```
[2021-12-17T16:02:53.408166+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-12-17T16:02:53.408428+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Drenso\\OidcBundle\\Security\\OidcAuthenticator"} []
[2021-12-17T16:02:53.918944+00:00] security.INFO: Authenticator failed. {"exception":"[object] (Drenso\\OidcBundle\\Security\\Exception\\OidcAuthenticationException(code: 0): Unable to verify JWT claims at /home/avitacco/Projects/php/secureshare/vendor/drenso/symfony-oidc-bundle/src/OidcClient.php:96)","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2021-12-17T16:02:53.919293+00:00] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"/login"} []
[2021-12-17T16:02:53.919923+00:00] security.DEBUG: The "Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator" authenticator set the failure response. {"authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
[2021-12-17T16:02:53.920138+00:00] security.DEBUG: The "Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator" authenticator set the response. Any later authenticator will not be called {"authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"} []
```

**Comment by bobvandevijver** [comment]
Okay, the logs indicate that the claims could not be verified. Can you use xdebug to see what is happening in the [`verifyJwtClaims`](https://github.com/Drenso/symfony-oidc/blob/master/src/OidcJwtHelper.php#L68) method? 

I'm mostly interested which comparison (on line 101-107) fails for you. Is it by any chance the `at_hash` one, or other maybe another one?

I might need to backport one of these two commits made to the Jumbojett repo:
- https://github.com/jumbojett/OpenID-Connect-PHP/commit/eaeb52064ec9dd0fe96b20df0f076b743fa9df63
- https://github.com/jumbojett/OpenID-Connect-PHP/commit/31913bfc361c0de89a2a0aa4a42424eaab6fc98d

**Comment by avitacco** [comment]
It is failing on line 102.

```php
$claims->iss = 'https://idp-stg.login.iu.edu';
$issuer = 'https://idp-stg.login.iu.edu/idp/shibboleth';
```

**Comment by bobvandevijver** [comment]
Okay, that means that the issuer value from the well known configuration endpoint (https://idp-stg.login.iu.edu/.well-known/openid-configuration) does not match with the value that is found in the `iss` claim inside the id token.

From the [spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation): "The issuer value returned MUST be identical to the Issuer URL that was directly used to retrieve the configuration information. This MUST also be identical to the iss Claim value in ID Tokens issued from this Issuer."

It seems I need to ask you to return to your provider and ask why the issuer from the well known does not match with the issuer in the token...

**Comment by avitacco** [comment]
@bobvandevijver I have brought this problem back to the team here who manage our authentication systems. I think they are out of the office and I'll be out of the office until 3 Jan.

**Comment by avitacco** [comment]
@bobvandevijver I hope you had good holidays and your new year is going well so far.

I was able to work with the people who run our auth service here and once they got the issuers to match everything just works on the non-jwt-access-token branch.

**Comment by bobvandevijver** [comment]
@avitacco Good to hear! I released V2 today, which includes the changes from the non-jwt branch, so I am closing this issue as resolved then 👍🏻
