### ISSUE TITLE
Add support for array as userIdentifier

### ISSUE THREAD

**Issue by JornJorn** [Drenso/symfony-oidc#12]
SURFconext Test IdP gives as user data:

![afbeelding](https://user-images.githubusercontent.com/81434299/158886395-3cd244fa-6e63-47d8-9dd9-550c25b4e44f.png)

We would like to use the uid as user identification, however, using an array (with only 1 value) as userIdentifier not supported right now. Is there a way to still use this? Or is there a way to alter the userIdentifier to get a value from this array before using it?

Thanks in advance

**Comment by bobvandevijver** [comment]
If you use the latest version of the bundle (v2.2.0), you can easily configure the used [user identifier](https://github.com/Drenso/symfony-oidc/blob/master/README.md#user-identifier) to read this value, using [Symfony Property Accessor](https://symfony.com/doc/current/components/property_access.html) syntax. For the first value in the `uids` array that would be as follows (which I copied from one of my own projects, so I'm certain it works).

```yaml
security:
  firewalls:
    main:
      oidc:
        user_identifier_property: uids[0]
```

However, I would advise against using this as user identifier as there is no control from SURF on the value of this field. It will work fine if you have only one provider that will keep this property stable. You should also be able to access this value from the Symfony token once authenticated, just use the `getUserData` method on the `OidcToken`.

https://github.com/Drenso/symfony-oidc/blob/aa9e14498affcce181ce56a81378146eeb4a196f/src/Security/Token/OidcToken.php#L29

But, if you're planning on using multiple authentication providers, the default `sub` is the way to go.
