### ISSUE TITLE
Configuration key "authorization_endpoint" does not exist.

### ISSUE THREAD

**Issue by chakib-lah** [Drenso/symfony-oidc#18]
Hello, 
I have a problem with authorization_endpoint, the client don't find my endpoint, I create a custom manager client with the correct authorization_endpoint but the problem is the bundle always take the default client. here my configuration 

      main:
            lazy: true
            oidc:
                provider: oidc_provider
                login_path: /gardian/login
                check_path: /gardian/login_check
                client: gardian
                user_identifier_property: nni

Action in the controller 

          /**
           * This controller forwards the user to the OIDC login
           *
           * @throws OidcException
           */
           #[Route('/gardian/login', name: 'login_oidc')]
          #[IsGranted('PUBLIC_ACCESS')]
          public function surfconext(OidcClientInterface $gardianOidcClient): RedirectResponse
         {
                // Redirect to authorization @ OIDC provider
                return $gardianClient->generateAuthorizationRedirect();
         }

configuration of the bundle

    drenso_oidc:
            #default_client: default # The default client, will be aliased to OidcClientInterface
            clients:
                default: # The client name, each client will be aliased to its name (for example, $defaultOidcClient)
                   # Required OIDC client configuration
                   well_known_url: '%env(OIDC_WELL_KNOWN_URL)%'
                   client_id: '%env(OIDC_CLIENT_ID)%'
                   client_secret: '%env(OIDC_CLIENT_SECRET)%'
                   redirect_route: '%env(OIDC_REDIRECT_ROUTE)%'
             gardian: # The client name, each client will be aliased to its name (for example, $gardianOidcClient)
                 # Required OIDC client configuration
                  well_known_url: '%env(OIDC_WELL_KNOWN_URL)%'
                  client_id: '%env(OIDC_CLIENT_ID)%'
                  client_secret: '%env(OIDC_CLIENT_SECRET)%'
                  redirect_route: '%env(OIDC_REDIRECT_ROUTE)%' 

      
I used the OidcClientLocator but I have the same problem.

in my use case a have another identity provider so OidcClient dosn't work for me i have to override  (generateAuthorizationRedirect methode) because my identity provider takes more paramets that are not available in

       $data = [
              'client_id'     => $this->clientId,
              'response_type' => 'code',
               'redirect_uri'  => $this->getRedirectUrl(),
               'scope'         => implode(' ', $scopes),
               'state'         => $this->generateState(),
                'nonce'         => $this->generateNonce(),
       ];
 Is it possible to do such thing ?

**Comment by bobvandevijver** [comment]
I'm not sure I understand your problem exactly, but the first thing that comes to mind is that you configured the `gardian` client exactly like the `default` client. You probably want to configure other values there, so you actually have a different client? Otherwise both client will be equal.

If you're trying to use your own extended implementation of the OidcClient class, you probably want to take a look at service decoration: https://symfony.com/doc/current/service_container/service_decoration.html. 

You can check the registered services with `bin/console debug:container drenso.oidc` & `bin/console debug:container drenso\oidc`. You're probably looking to override `drenso.oidc.client.gardian`.

But, can you tell me a bit more about how you would expect your redirect url to look like? Are those extra parameters static?

**Comment by chakib-lah** [comment]
yes we had more extra parameters static, and the bundle didn't find my endpoint here un exemple we used with V1 

    <?php
       
      namespace App\Security;
       
      use Drenso\OidcBundle\OidcClient;
      use Drenso\OidcBundle\OidcTokens;
      use Symfony\Component\HttpFoundation\Request;
      use Symfony\Component\Routing\RouterInterface;
      use Symfony\Component\HttpFoundation\RedirectResponse;
      use Drenso\OidcBundle\Exception\OidcConfigurationException;
      use Symfony\Component\HttpFoundation\Session\SessionInterface;
      use Drenso\OidcBundle\Exception\OidcConfigurationResolveException;
      use Drenso\OidcBundle\Security\Exception\OidcAuthenticationException;
       
                        class OidcGardianClient extends OidcClient
                  {
                      private string $clientId;
                      private string $clientSecret;
                      private ?string $redirectRoute;
                      private string $chainAuth;
                   
                      public function __construct(SessionInterface $session, RouterInterface $router, string $wellKnownUrl, string $clientId, string $clientSecret, string $chainAuth, ?string $redirectRoute = 'login_check')
                      {
                          parent::__construct($session, $router, $wellKnownUrl, $clientId, $clientSecret, $redirectRoute);
                          $this->clientId = $clientId;
                          $this->clientSecret = $clientSecret;
                          $this->redirectRoute = $redirectRoute;
                          $this->chainAuth = $chainAuth;
                      }
                   
                      /**
                       * Authenticate the incoming request
                       *
                       * @param Request $request
                       *
                       * @return OidcTokens|null
                       * @throws OidcException
                       */
                      public function authenticate(Request $request)
                      {
                          // Check whether the request has an error state
                          if ($request->request->has('error')) {
                              throw new OidcAuthenticationException(sprintf(
                                  "OIDC error: %s. Description: %s.",
                                  $request->request->get('error', ''),
                                  $request->request->get('error_description', '')
                              ));
                          }
                   
                          // Check whether the request contains the required state and code keys
                          $code  = $request->query->get('code');
                          $state = $request->query->get('state');
                          if ($code == NULL || $state == NULL) {
                              return NULL;
                          }
                   
                          // Do a session check
                          if ($state != $request->getSession()->get(self::OIDC_SESSION_STATE)) {
                              // Fail silently
                              return NULL;
                          }
                   
                          // Clear session after check
                          $request->getSession()->remove(self::OIDC_SESSION_STATE);
                   
                          // Request the tokens
                          $tokens = $this->requestTokens($code);
                   
                          // Retrieve the claims
                          $claims = $this->jwtHelper->decodeJwt($tokens->getIdToken(), 1);
                   
                          // Verify the token
                          if (!$this->jwtHelper->verifyJwtSignature($this->getJwktUri(), $tokens)) {
                              throw new OidcAuthenticationException("Unable to verify signature");
                          }
                   
                          // If this is a valid claim
                          if ($this->jwtHelper->verifyJwtClaims($this->getIssuer(), $claims, $tokens)) {
                              return $tokens;
                          } else {
                              throw new OidcAuthenticationException("Unable to verify JWT claims");
                          }
                      }
                   
                      /**
                       * Create the redirect that should be followed in order to authorize
                       *
                       * @param string|null $prompt One of 'none', 'login', 'consent', 'select_account' or 'create'
                       *                            If null or not supplied, the parameter will be omitted from the request
                       *                            Note that 'create' is currently in draft and might not be supported by every implementation
                       * @param string[]    $scopes An array of scopes to request
                       *                            If not supplied it will default to openid
                       *
                       * @return RedirectResponse
                       * @throws OidcConfigurationException
                       * @throws OidcConfigurationResolveException
                       */
                      public function generateAuthorizationRedirect(?string $prompt = NULL, array $scopes = ['openid']): RedirectResponse
                      {
                          $data = [
                              'client_id'     => $this->clientId,
                              'response_type' => 'code',
                              'redirect_uri'  => $this->getRedirectUrl(),
                              'scope'         => implode(' ', $scopes),
                              'state'         => $this->generateElement(self::OIDC_SESSION_STATE),
                              'nonce'         => $this->generateElement(self::OIDC_SESSION_NONCE),
                              'acr_values'    => $this->chainAuth,
                          ];
                   
                          if ($prompt) {
                              $validPrompts = ['none', 'login', 'consent', 'select_account', 'create'];
                              if (!in_array($prompt, $validPrompts)) {
                                  throw new \InvalidArgumentException(sprintf(
                                      'The prompt parameter need to be one of ("%s"), but "%s" given',
                                      implode('", "', $validPrompts),
                                      $prompt
                                  ));
                              }
                   
                              $data['prompt'] = $prompt;
                          }
                          return new RedirectResponse(sprintf('%s?%s', $this->getAuthorizationEndpoint(), http_build_query($data)));
                      }
                   
                      public function deconnect(OidcTokens $token, string $redirectLogout = 'logged_out')
                      {
                          $data = [
                              'id_token_hint' => $token->getIdToken(),
                              'post_logout_redirect_uri' => $this->router->generate($redirectLogout, [], RouterInterface::ABSOLUTE_URL),
                          ];
                   
                          $this->urlFetcher->fetchUrl(sprintf('%s?%s', $this->getDeconnect(), http_build_query($data)));
                      }
                   
                      protected function getAuthorizationEndpoint()
                      {
                          return $this->wellKnownUrl . '/authorize';
                      }
                   
                      protected function getIssuer()
                      {
                          return str_replace('.com', '.com:443', $this->wellKnownUrl);
                      }
                   
                      protected function getJwktUri()
                      {
                          return $this->wellKnownUrl . '/connect/jwk_uri';
                      }
                   
                      protected function getTokenEndpoint()
                      {
                          return $this->wellKnownUrl . '/access_token';
                      }
                   
                      protected function getUserinfoEndpoint()
                      {
                          return $this->wellKnownUrl . '/userinfo';
                      }
                   
                      protected function getDeconnect()
                      {
                          return $this->wellKnownUrl . '/connect/endSession';
                      }
                   
                      /**
                       * Generate Stat/Nonce
                       *
                       * @return string
                       */
                      private function generateElement(string $nameSession): string
                      {
                          $value = md5(openssl_random_pseudo_bytes(25));
                   
                          $this->session->set($nameSession, $value);
                   
                          return $value;
                      }
                   
                      /**
                       * Request the tokens from the OIDC provider
                       *
                       * @param $code
                       *
                       * @return OidcTokens
                       *
                       * @throws OidcConfigurationException
                       * @throws OidcConfigurationResolveException
                       * @throws OidcException
                       */
                      private function requestTokens($code)
                      {
                          $params = [
                              'grant_type'    => 'authorization_code',
                              'code'          => $code,
                              'redirect_uri'  => $this->getRedirectUrl(),
                              'client_id'     => $this->clientId,
                              'client_secret' => $this->clientSecret,
                          ];
                   
                          // Use basic auth if offered
                          $headers = [];
                          $headers = ['Authorization: Basic ' . base64_encode($this->clientId . ':' . $this->clientSecret)];
                          unset($params['client_secret']);
                   
                          $jsonToken = json_decode($this->urlFetcher->fetchUrl($this->getTokenEndpoint(), $params, $headers));
                   
                          // Throw an error if the server returns one
                          if (isset($jsonToken->error)) {
                              if (isset($jsonToken->error_description)) {
                                  throw new OidcAuthenticationException($jsonToken->error_description);
                              }
                              throw new OidcAuthenticationException(sprintf('Got response: %s', $jsonToken->error));
                          }
                   
                          return new OidcTokens($jsonToken);
                      }
                  }

but with V2 we have problems, we can't ovrride `authorization_endpoint` and i have more parameteres to send in function `generateAuthorizationRedirect` like we did with V1.

**Comment by bobvandevijver** [comment]
You will want to take a look at service decoration as mentioned before. It should look something like this:

```php
#[AsDecorator(decorates: drenso.oidc.client.gardian)]
class YourOidcClient extends OidcClient {
  // Do whatever you need to do.
}
```

Still curious on why you need to override the `authorization_endpoint` though, as that should be quite fixed from the well known. If the well known is wrong, you should maybe put your effort in fixing that instead.

**Comment by chakib-lah** [comment]
Thank you for your response. It was helpful using decorates, it helps me to override the class OidcCLient, because I have to add manually all configuration for my client Gardian because he has more parameters to send.
