### ISSUE TITLE
Facebook OIDC configuration doesn't contain "token_endpoint_auth_methods_supported"

### ISSUE THREAD

**Issue by Frikkle** [Drenso/symfony-oidc#19]
Heya, I was trying to set up your bundle in a Symfony 6.1 project and pointing it at Facebook for OIDC connectivity (using their configuration endpoint as specified on https://developers.facebook.com/docs/facebook-login/limited-login/token/)

However, authentication seems to fail, after some digging around and adding some dumps to the `OidcClient`, I figured out that it fails inside of the `getConfigurationValue(string $key)` method, as it is looking for the key `token_endpoint_auth_methods_supported` in the configuration, but this key isn't present. See the screenshot below for the dumped config object.

![image](https://user-images.githubusercontent.com/9324165/187096808-b6e379c4-1acc-4cbd-8392-a7e6d535d622.png)

Any clue how to proceed and/or combat this? :) If there's anything I can do to help out, provide more info, etc, let me know :)

**Comment by Frikkle** [comment]
I did some googling and it seems that FB doesn't fully implement OIDC. Would there be some way to configure this bundle to relax on some checks (or default to a certain communication flow) for cases like this? 🤔 

https://stackoverflow.com/questions/24402151/openid-connect-configuration-for-facebook

**Comment by bobvandevijver** [comment]
I did not even know Facebook was offering OIDC at all, but why am I not surprised that they do not adhere to the standard?

You might be better of by switching to OAuth2, which Facebook should support correctly. You can take a look at https://github.com/knpuniversity/oauth2-client-bundle, which has a dedicated Facebook provider: https://github.com/thephpleague/oauth2-facebook.

**Comment by Frikkle** [comment]
Thanks for the reply! I currently have OAuth fully implemented using https://github.com/hwi/HWIOAuthBundle which works pretty well for several providers. The thing is, though, that I read that "abusing" the regular OAuth2 flows for account registration is not a valid means of authenticating a user and that one should use OIDC for that. Hence me being here 🙂

The issue with OAuth2 for authentication lies with the fact that the token you get allows access to _some_ resource, not per se a resource of the User you're trying to identify. For that, you should do some form of token introspection, which OIDC offers, but OAuth2 does not out of the box.

Currently, I have token introspection built in by hand for each of my supported OAuth providers, but if OIDC would offer one integrated standardised solution for this, it would have been awesome :)

**Comment by Frikkle** [comment]
But it seems that OIDC support out there in the wild is still pretty thin :'(

**Comment by bobvandevijver** [comment]
Lets see, maybe we can think of something that might help with #18 as well. Do you think that if there is an easy way to extend/override the well known response (so, add/rewrite certain keys in the JSON response) it could solve the issue? In your case, you would need to add the `token_endpoint_auth_methods_supported` key to something that is supported.

**Comment by chakib-lah** [comment]
Here how I override class oidcClient 

   
      namespace App\Security;
          
      use Drenso\OidcBundle\Exception\OidcException;
      use Drenso\OidcBundle\Model\OidcTokens;
      use Drenso\OidcBundle\OidcClient;
      use Drenso\OidcBundle\OidcJwtHelper;
      use Drenso\OidcBundle\OidcSessionStorage;
      use Drenso\OidcBundle\OidcUrlFetcher;
      use Drenso\OidcBundle\Security\Exception\OidcAuthenticationException;
      use InvalidArgumentException;
      use LogicException;
      use RuntimeException;
      use Symfony\Component\HttpFoundation\RedirectResponse;
      use Symfony\Component\HttpFoundation\Request;
      use Symfony\Component\HttpFoundation\RequestStack;
      use Symfony\Component\Security\Core\Security;
      use Symfony\Component\Security\Http\HttpUtils;
      use Symfony\Contracts\Cache\CacheInterface;
      
      class GardianOidcClient extends OidcClient
      {
      
          /** OIDC configuration values */
          protected ?array $configuration = null;
          private ?string $cacheKey = null;
      
          public function __construct(
              protected RequestStack       $requestStack,
              protected HttpUtils          $httpUtils,
              protected ?CacheInterface    $wellKnownCache,
              protected OidcUrlFetcher     $urlFetcher,
              protected OidcSessionStorage $sessionStorage,
              protected OidcJwtHelper      $jwtHelper,
              protected string             $wellKnownUrl,
              private ?int                 $wellKnownCacheTime,
              private string               $clientId,
              private string               $clientSecret,
              private string               $redirectRoute,
              private string               $chainAuth,
              private string               $rememberMeParameter
          )
          {
              parent::__construct($requestStack, $httpUtils, $wellKnownCache, $urlFetcher, $sessionStorage, $jwtHelper,
                  $wellKnownUrl, $wellKnownCacheTime, $clientId, $clientSecret, $redirectRoute, '');
              // Check for required phpseclib classes
              if (!class_exists('\phpseclib\Crypt\RSA') && !class_exists('\phpseclib3\Crypt\RSA')) {
                  throw new RuntimeException('Unable to find phpseclib Crypt/RSA.php.  Ensure phpseclib/phpseclib is installed.');
              }
      
              if (!$this->wellKnownUrl || filter_var($this->wellKnownUrl, FILTER_VALIDATE_URL) === false) {
                  throw new LogicException(sprintf('Invalid well known url (%s) for OIDC', $this->wellKnownUrl));
              }
              $this->configuration = [
                  'authorization_endpoint' => $this->wellKnownUrl . '/authorize',
                  'issuer' => str_replace('.com', '.com:443', $this->wellKnownUrl),
                  'jwks_uri' => $this->wellKnownUrl . '/connect/jwk_uri',
                  'token_endpoint' => $this->wellKnownUrl . '/access_token',
                  'userinfo_endpoint' => $this->wellKnownUrl . '/userinfo'
              ];
          }
      
          /** {@inheritDoc} */
          public function authenticate(Request $request): OidcTokens
          {
              // Check whether the request has an error state
              if ($request->request->has('error')) {
                  throw new OidcAuthenticationException(sprintf('OIDC error: %s. Description: %s.',
                      $request->request->get('error', ''), $request->request->get('error_description', '')));
              }
      
              // Check whether the request contains the required state and code keys
              if (!$code = $request->query->get('code')) {
                  throw new OidcAuthenticationException('Missing code in query');
              }
              if (!$state = $request->query->get('state')) {
                  throw new OidcAuthenticationException('Missing state in query');
              }
      
              // Do a session check
              if ($state != $this->sessionStorage->getState()) {
                  // Fail silently
                  throw new OidcAuthenticationException('Invalid session state');
              }
      
              // Clear session after check
              $this->sessionStorage->clearState();
      
              // Request and verify the tokens
              return $this->verifyTokens(
                  $this->requestTokens('authorization_code', $code, $this->getRedirectUrl())
              );
          }
      
          /** {@inheritDoc} */
          public function refreshTokens(string $refreshToken): OidcTokens
          {
              // Clear session after check
              $this->sessionStorage->clearState();
      
              // Request and verify the tokens
              return $this->verifyTokens(
                  $this->requestTokens('refresh_token', null, null, $refreshToken),
                  verifyNonce: false
              );
          }
      
          public function generateAuthorizationRedirect(?string $prompt = null, array $scopes = ['openid'], bool $forceRememberMe = false): RedirectResponse
          {
              $data = [
                  'client_id' => $this->clientId,
                  'client_secret' => $this->clientSecret,
                  'response_type' => 'code',
                  'redirect_uri' => $this->getRedirectUrl(),
                  'scope' => implode(' ', $scopes),
                  'state' => $this->generateState(),
                  'nonce' => $this->generateNonce(),
                  'acr_values' => $this->chainAuth,
              ];
      
              if ($prompt) {
                  $validPrompts = ['none', 'login', 'consent', 'select_account', 'create'];
                  if (!in_array($prompt, $validPrompts)) {
                      throw new InvalidArgumentException(sprintf(
                          'The prompt parameter need to be one of ("%s"), but "%s" given',
                          implode('", "', $validPrompts),
                          $prompt
                      ));
                  }
      
                  $data['prompt'] = $prompt;
              }
      
              // Store remember me state
              /** @phan-suppress-next-line PhanAccessMethodInternal */
              $parameter = $this->requestStack->getCurrentRequest()->get($this->rememberMeParameter);
      
              $this->sessionStorage->storeRememberMe($forceRememberMe || 'true' === $parameter || 'on' === $parameter || '1' === $parameter || 'yes' === $parameter || true === $parameter);
      
              // Remove security session state
              $session = $this->requestStack->getSession();
              $session->remove(Security::AUTHENTICATION_ERROR);
              $session->remove(Security::LAST_USERNAME);
      
              $endpointHasQuery = parse_url($this->getAuthorizationEndpoint(), PHP_URL_QUERY);
      
              return new RedirectResponse(sprintf('%s%s%s', $this->getAuthorizationEndpoint(), $endpointHasQuery ? '&' : '?', http_build_query($data)));
          }
      
          protected function getRedirectUrl(): string
          {
              return $this->httpUtils->generateUri($this->requestStack->getCurrentRequest(), $this->redirectRoute);
          }
      
          /** Generate a nonce to verify the response */
          private function generateNonce(): string
          {
              $value = $this->generateRandomString();
      
              $this->sessionStorage->storeNonce($value);
      
              return $value;
          }
      
          /** Generate a secure random string for usage as state */
          private function generateRandomString(): string
          {
              return md5(openssl_random_pseudo_bytes(25));
          }
      
          /** Generate a state to identify the request */
          private function generateState(): string
          {
              $value = $this->generateRandomString();
              $this->sessionStorage->storeState($value);
      
              return $value;
          }
      
          /**
           * Request the tokens from the OIDC provider.
           *
           * @throws OidcException
           */
          private function requestTokens(string $grantType, string $code = null, string $redirectUrl = null, string $refreshToken = null): OidcTokens
          {
              $params = [
                  'grant_type' => $grantType,
                  'client_id' => $this->clientId,
                  'client_secret' => $this->clientSecret,
              ];
      
              if (null !== $code) {
                  $params['code'] = $code;
              }
      
              if (null !== $redirectUrl) {
                  $params['redirect_uri'] = $redirectUrl;
              }
      
              if (null !== $refreshToken) {
                  $params['refresh_token'] = $refreshToken;
              }
      
              // Use basic auth if offered
              $headers = ['Authorization: Basic ' . base64_encode($this->clientId . ':' . $this->clientSecret)];
              unset($params['client_secret']);
      
      
              $jsonToken = json_decode($this->urlFetcher->fetchUrl($this->getTokenEndpoint(), $params, $headers));
      
              // Throw an error if the server returns one
              if (isset($jsonToken->error)) {
                  if (isset($jsonToken->error_description)) {
                      throw new OidcAuthenticationException($jsonToken->error_description);
                  }
                  throw new OidcAuthenticationException(sprintf('Got response: %s', $jsonToken->error));
              }
      
              return new OidcTokens($jsonToken);
          }
      
          /** @throws OidcException */
          private function verifyTokens(OidcTokens $tokens, $verifyNonce = true): OidcTokens
          {
              // Retrieve the claims
              $claims = $this->jwtHelper->decodeJwt($tokens->getIdToken(), 1);
      
              // Verify the token
              if (!$this->jwtHelper->verifyJwtSignature($this->getJwktUri(), $tokens)) {
                  throw new OidcAuthenticationException('Unable to verify signature');
              }
      
              // If this is a valid claim
              if ($this->jwtHelper->verifyJwtClaims($this->getIssuer(), $claims, $tokens, $verifyNonce)) {
                  return $tokens;
              } else {
                  throw new OidcAuthenticationException('Unable to verify JWT claims');
              }
          }
      
          /**
           * @return string
           */
          public function getDeconnect(): string
          {
              return $this->wellKnownUrl . '/connect/endSession';
          }
      
      } `

And in the services.yaml I add my decorates 
       
               App\Security\GardianOidcClient:
                      decorates: drenso.oidc.client.default
                      arguments:
                          $urlFetcher: '@drenso.oidc.url_fetcher.default'
                          $sessionStorage: '@drenso.oidc.session_storage.default'
                          $jwtHelper: '@drenso.oidc.jwt_helper.default'
                          $wellKnownUrl: '%env(OIDC_WELL_KNOWN_URL)%'
                          $clientId: '%env(OIDC_CLIENT_ID)%'
                          $clientSecret: '%env(OIDC_CLIENT_SECRET)%'
                          $redirectRoute: '%env(OIDC_REDIRECT_ROUTE)%'
                          $chainAuth: '%env(OIDC_CHAIN_AUTH)%'
                          $wellKnownCacheTime: null
                          $rememberMeParameter: 'false'

And it works.

**Comment by bobvandevijver** [comment]
@chakib-lah  Looks like you have overriden quite a lot, not sure whether that is necessary for your use. I also think that using the proposed well known parser it would be a lot easier for you as wel..

**Comment by Frikkle** [comment]
> Lets see, maybe we can think of something that might help with #18 as well. Do you think that if there is an easy way to extend/override the well known response (so, add/rewrite certain keys in the JSON response) it could solve the issue? In your case, you would need to add the `token_endpoint_auth_methods_supported` key to something that is supported.

That would indeed help out for this issue and/or other non-spec-compliant parties. I was thinking about decorating some stuff in order to override certain behaviour, but your solution sounds a lot cleaner.

**Comment by bobvandevijver** [comment]
@Frikkle Can you see whether the `19-well-known-parser` branch helps you? See https://github.com/Drenso/symfony-oidc/commit/9c225e03552f59c0aa9a1465dc4f9848433ade3a for the instructions.

You should be able to install the branch with `composer req drenso/symfony-oidc-bundle:dev-19-well-known-parser`

**Comment by chakib-lah** [comment]
Hello, it worked with Well Known parser, and We can add all configuration that required.

But for me I have a little issue :) my client didn't know the function `urlencode` when he encrypts the `client_id` and  `client_secret` I have this error `invalid_client` and he worked when I use only `base64_encode` 

`$headers = ['Authorization: Basic ' . base64_encode(urlencode($this->clientId) . ':' . urlencode($this->clientSecret))];`  Failed

`$headers = ['Authorization: Basic ' . base64_encode($this->clientId . ':' . $this->clientSecret)];` Success

Thank you for your answer.  :)

**Comment by bobvandevijver** [comment]
@chakib-lah Please contact your identity provider as they are in violation of the specification. The `clientId` and `clientSecret` must be url encoded according to [rfc6749](https://www.rfc-editor.org/rfc/rfc6749#section-2.3.1). This was also backported to the original upstream, see https://github.com/jumbojett/OpenID-Connect-PHP/pull/192.

**Comment by chakib-lah** [comment]
I wish they can do that, and they are stubborn. I will aske them to do that. :)

**Comment by Frikkle** [comment]
> t your identity provider as they are in violation of the specification.

Thanks Bob for the prompt action! I'll have a look one of these days, probably on Thursday.

**Comment by bobvandevijver** [comment]
@Frikkle Did you have the chance to test this?

**Comment by bobvandevijver** [comment]
Closing this as _hopefully_ solved, the well-known parser support has been made available with [v2.6.0](https://github.com/Drenso/symfony-oidc/releases/tag/v2.6.0).
