### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by hockdudu** [Drenso/symfony-oidc#21]
I noticed this project doesn't have a license file.

The project appears to be licensed with the Apache 2.0 license in the `composer.json`[^current-license], but this doesn't fulfill the license requirements about the recipients receiving a copy of the license ([related StackExchange thread](https://opensource.stackexchange.com/a/8816)).

[^current-license]: https://github.com/Drenso/symfony-oidc/blob/986fd46d763520dc95001a8e7e86d0112eabb335/composer.json#L11

**Comment by bobvandevijver** [comment]
Missing license has been added with 8700de5685e566ef1572522792ab048a78d9d9c5, thank you for the notice (even though I believe this to be a waste of storage and bandwidth).
