### ISSUE TITLE
Authentication token during ensureUserExists

### ISSUE THREAD

**Issue by shylux** [Drenso/symfony-oidc#35]
Hi, i need the authentication token in ensureUserExists to access a profile endpoint to retrieve data to populate a new profile.

On v1 I used `loadUserByToken(OidcToken $token)` but this changed to `ensureUserExists(string $userIdentifier, OidcUserData $userData)` where i only have the `OidcUserData` object.

How can i do this in v2? Do i have to overwrite the `OidcClient` class for a custom `retrieveUserInfo`?

**Comment by bobvandevijver** [comment]
If I understand you correctly, the information as returned from the OIDC provider user info endpoint isn't enough for your use case and you need to retrieve additional data from another endpoint that is not related to the OIDC authentication flow?

In that case, yes, overriding the `OidcClient` would work. You can probably skip the original implementation of that method, but you will still need to return an `OidcUserData` object (which should be flexible enough for your use case I guess).

I would be open for a PR where the `OidcTokens` object is also passed to the `ensureUserExists` method, but as that would be a breaking change it will trigger a new major version.

**Comment by shylux** [comment]
Thank you, yes you understood perfectly.

I can stull all the data in `OidcUserData` so that should work.

Here the implementation if anyone needs to do the same:

![image](https://github.com/Drenso/symfony-oidc/assets/1375745/9c6bb461-d2f1-4a6c-9976-f210d892aa6d)

![image](https://github.com/Drenso/symfony-oidc/assets/1375745/9dfe27cd-dc0a-462a-9b1f-93ad9f9dad6e)

**Comment by bobvandevijver** [comment]
@shylux Alright! Instead of defining the service and its argument fully in your config, you might be better off if you use [service decoration](https://symfony.com/doc/current/service_container/service_decoration.html) instead. You will need to implement the `OidcClientInterface` on your class and add some forwarding methods, but it should save the trouble when the `OidcClient` arguments change (as they will still be populated by this bundle).

**Comment by shylux** [comment]
@bobvandevijver I considered that as it would be more robust to change. But I can't add data to the `OidcUserData` object. I also can't get all the data and construct a new one. So overriding the service seemed to be the only option.

**Comment by bobvandevijver** [comment]
Fair enough. If you want to reduce code duplication I would be open for a PR that add a method to retrieve all data from the `OidcUserData` object.

**Comment by lbenz** [comment]
Decorate `OidcClient` throught `OidcClientInterface` is the best practice but you have to implement all methods and use the `inner` object for all method to keep the behaviour. I think it is easier to use compiler pass, consider example below: 

```
// src/Kernel.php
class Kernel implements CompilerPassInterface
{
    public function process(ContainerBuilder $container): void
    {
        $container->getDefinition(DrensoOidcExtension::CLIENT_ID.'.default')->setClass(CustomOidcClient::class);
    }
}
```
