### ISSUE TITLE
UserProvider

### ISSUE THREAD

**Issue by avamdui** [Drenso/symfony-oidc#36]
Hello There,
Can someone have an exemple of his : 
Security.yaml
Drenso_oidc.yaml
LoginController.php
Userprovider.php
I can't find a way to get OIDC working, i think i am missing things.
Thinks !

**Comment by bobvandevijver** [comment]
The examples for those files are all in the readme: https://github.com/Drenso/symfony-oidc/blob/master/README.md? What doesn't work for you?

**Comment by svinohod** [comment]
Where can I find example for UserProvider ?

**Comment by bobvandevijver** [comment]
See the [Symfony docs](https://symfony.com/doc/current/security/user_providers.html) and combine that knowledge with the [readme](https://github.com/Drenso/symfony-oidc#user-provider).
