### ISSUE TITLE
Link to our example project

### ISSUE THREAD

**Issue by muhlemmer** [Drenso/symfony-oidc#47]
My current workplace is an identity provider and we wanted to publish an example symfony project that uses OIDC with our product. Although I'm not a PHP engineer, it was quite straightforward to get started with Symfony and this OIDC bundle. Kudos for that!

I came across #1, where you mentioned:

> I currently do not know of any project that uses this library, and is open source at the same time. 

Well, we are a open source company and naturally our example is also open source :smile: . If it is is not a conflict with your own business, I would like to add a link to our project in your README.

https://github.com/zitadel/example-symfony-oidc

Thanks!

**Comment by bobvandevijver** [comment]
Sure, we can add a link to the readme! Can you create a PR to add a segment of known usages/examples in OS projects? I think at the end would be the best place.
