### ISSUE TITLE
Can I get Access Token AFTER Authentication?

### ISSUE THREAD

**Issue by svinohod** [Drenso/symfony-oidc#49]
I see _accessToken_ value in PHP Session. Can I get this by symfony-oidc-Library or by Symfony APIs ?

**Versions**
Symfony 6.4
drenso/symfony-oidc-bundle 2.13.0

**Comment by bobvandevijver** [comment]
You can access the `OidcToken` by retrieving the Token from the Symfony token storage (so, the Symfony security component, TokenStorageInterface, `->getToken()`). Once you have the token, you can access the `OidcTokens` (note the plural) with `->getAuthData()`, which contains both the access and refresh tokens.
