### ISSUE TITLE
Really slow response time for /login_check

### ISSUE THREAD

**Issue by benr77** [Drenso/symfony-oidc#54]
I am seeing really slow response times for the `/login_check` endpoint. 

It is ~4 seconds in the `dev` environment - I see in the profiler that `TraceableFirewallListener` is taking almost all of this time.

Then I compared this to the time for the `/login_check` endpoint in my `prod` environment and it's roughly the same 4 seconds, so I don't think it's any debugging / profiling overhead particularly.

Any ideas what could be causing the endpoint to take so long to return a response?

Thanks!

**Comment by bobvandevijver** [comment]
It is most probably the identity provider slowing you down there.

**Comment by benr77** [comment]
Do you mean the external system? e.g. Zitadel / Keycloak?

**Comment by bobvandevijver** [comment]
Yes, I do. During authentication (executed the `login_check`) this userinfo endpoint of the IdP is queried, and that is probably what is taking up the time there. Also, if the well known cache isn't working for you, it might actually be two requests to the IdP.

You can easily confirm this by placing a breakpoint in the authenticator and see what's taking long. For my production projects, the `/login_check` request takes about 250ms.

https://github.com/Drenso/symfony-oidc/blob/02da10e7d03f4f575a6bb9094e882422b8b55787/src/Security/OidcAuthenticator.php#L61

Note that that I am assuming that you do not have any other authenticator configured. Any authenticator that indicates it could handle the incoming request and has higher priority will be executed as well. Without a full timing profile it won't be possible to be sure anyways.

**Comment by benr77** [comment]
Thank you for your comprehensive explanation. I definitely have issues with the speed of the provider, so I'll investigate this route. Cheers!
