### ISSUE TITLE
Local logout option in generateEndSessionEndpointRedirect function

### ISSUE THREAD

**Issue by KevinGrand49** [Drenso/symfony-oidc#56]
Hello,

Would it be possible to add an optional parameter to the OidcClient generateEndSessionEndpointRedirect function?

According to the documentation (https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout):

>  It is up to the RP whether to locally log out the End-User before redirecting the User Agent to the OP's Logout Endpoint. On one hand, if the End-User approves the logout at the OP, the RP initiating the logout should receive a logout message from the OP and can perform a local logout at that time. On the other hand, some logout notification methods from the OP to the RP are unreliable and therefore the notification might not be received. Also, the End-User might not approve the OP logging out, in which case the RP would not receive a logout notification. 

This would avoid overwriting / decorating the functionality just to kill the token when you want to disconnect the application manually.

If it's possible, I'll leave it up to you how you implement it.
```php
# In generateEndSessionEndpointRedirect function
# ...

if (null !== $postLogoutRedirectUrl) {
    $data = array_merge($data, [
        'post_logout_redirect_uri' => $postLogoutRedirectUrl,
    ]);
}

###############################################
// Implementation of conditional local logout 
###############################################

$endpointHasQuery = parse_url($this->endSessionEndpoint, PHP_URL_QUERY);

return new RedirectResponse(
    sprintf(
        '%s%s%s',
        $this->endSessionEndpoint,
        $endpointHasQuery ? '&' : '?', http_build_query($data))
);
```

**Comment by bobvandevijver** [comment]
I'm not sure whether I understand your question. If you want to kill the Symfony session, you can use the Symfony security logout handler, which will automatically forward the user to the `end_session_endpoint` when enabled in the firewall configuration (see `enable_end_session_listener` in the readme). 

We only support the local logout (with optional redirect), not on message from the OpenID provider.
