### ISSUE TITLE
well_known_parser is never called

### ISSUE THREAD

**Issue by axel37** [Drenso/symfony-oidc#59]
Hi,

I need to hook up my app with an OIDC provider that does not supply a "well-known" url, so I was thinking of injecting all the config through a `well_known_parser`.

However, after setting one up (I called it `CustomWellKnownParser`), it's never called. I know it has been taken into account, since I can see it while inspecting the `OidcClient` in a debugger :

![A screenshot of a debugger showing the the customWellKnownParser is part of the OidcClient](https://github.com/Drenso/symfony-oidc/assets/11683059/f9de614e-88cb-47bb-a7fc-a11bff7329c7)

> (No sensitive information here, it's a local test environment)

To test whether the custom parser was being called, I tried setting a breakpoint there (not hit) and changing the `$config` array (the change is never reflected).

**Comment by bobvandevijver** [comment]
The well-known parser is only used after the config has been retrieved successfully:

https://github.com/Drenso/symfony-oidc/blob/4ebc10693694f088e424123027ac9abaf4351413/src/OidcClient.php#L488

Not having a well-known endpoint makes your provider not OIDC-complaint, and more importantly, insecure as there is no way to retrieve the keys required to validate the tokens. I would advise you to run away from them and use a different provider that does adhere to the OIDC-standard.

**Comment by axel37** [comment]
> I would advise you to run away from them and use a different provider

Unfortunately, that is not an option. It's the company's internal identity provider, and I don't have that kind of power.

> there is no way to retrieve the keys required to validate the tokens

It does provide a `jwk_uri` route, if that's what being discussed here.

___

> The well-known parser is only used after the config has been retrieved successfully:

Testing with a valid OIDC provider shows that it's still not being called.

**Comment by bobvandevijver** [comment]
Good to hear it was indeed the cache 👍🏻
