### ISSUE TITLE
Example Project or insights for Keycloak and Angular API

### ISSUE THREAD

**Issue by dgrevink** [Drenso/symfony-oidc#65]
First, thanks for making available the code, it seems really good !

I see that you have a link to an example for Zitadel.

Do you have a similar link for a sample project using Keycloak ?

Hope you can help me !

All the best,

David

**Comment by bobvandevijver** [comment]
The Zitadel example has been provided by Zitadel themselves, who have submitted the example link which we accepted. There are no other examples project available for other providers, but it should al be quite similar. I'm confident that if you follow the Zitadel guide but configure Keycloak instead you will get it to work in no time.

I am using Keycloak myself, but that project is not open source so I cannot share that with you.
