### ISSUE TITLE
Limitations to pass idP adapter (pfidpadapterid) details 

### ISSUE THREAD

**Issue by shreelakshmi-u** [Drenso/symfony-oidc#7]
We  are unable to pass additional parameter idP adapter (pfidpadapterid) details as the constructor accepts only $wellKnownUrl,  $clientId,  $clientSecret parameters. Is there a possibility to pass the idP adapter details to the oidcclient?

**Comment by bobvandevijver** [comment]
If I'm correct, you only need to pass this parameter when authorizing a new client, right? If so, you can either:

1. Extend the `OidcClient` class with your own and override the `generateAuthorizationRedirect` method to add your required parameters to the OIDC `RedirectResponse`
2. Create an PR to add support for custom authorization redirect parameters. You can think of configuring default parameters, of adding an extra parameter to the `generateAuthorizationRedirect` to set extra parameters on the fly.

**Comment by shreelakshmi-u** [comment]
Yes we did as mentioned in the readme in both service.yml and security.yml. We could see the control is going to the OidcListener  constructor but "attemptAuthentication" is not called. Are we missing something? or we need to call this function explicitly?

**Comment by bobvandevijver** [comment]
No, the `attemptAuthentication` is used by the Symfony firewall internally. It will only be called when the user is returned after a successful authentication at the IdP.

**Comment by shreelakshmi-u** [comment]
Thanks, now  we could find the calls to listeners and authenticating successfully. On success it has to redirect to the login_check route. But we observed "onAuthenticationSuccess" is calling determineTargetUrl() and it is always  taking  the $this->options['default_target_path']  and it has "/".  Do we need to add a custom "onAuthenticationSuccess"  function? or we need to do any additional setting in the service.yml ?

**Comment by bobvandevijver** [comment]
You can either write a custom event listener for the event, or use the security configuration for this ([form_login example](https://symfony.com/doc/current/security/form_login.html#changing-the-default-page)).

All these questions are about understanding how the Symfony security component work. I can recommend to read it's documentation.
