### ISSUE TITLE
refreshTokens scope

### ISSUE THREAD

**Issue by gregoire-jianda** [Drenso/symfony-oidc#76]
Hi,

First, thanks a lot for this bundle :)

I'm running into an issue with the refreshTokens method : the new access token issues by my IAM doesn't have the scopes originally defined on login.
My LoginController sets the following scopes : 
```
$oidcClient->generateAuthorizationRedirect(null, ['openid', 'email', 'profile']);
```

If I grossly force scopes in the refreshTokens method, the refreshed token is fine : 
```
public function refreshTokens(string $refreshToken): OidcTokens
  {
    // Clear session after check
    $this->sessionStorage->clearState();

    // Request and verify the tokens
    $scopes = ['openid', 'email', 'profile'];
    return $this->verifyTokens(
      $this->requestTokens('refresh_token', refreshToken: $refreshToken, scope: implode(' ', $scopes)),
      verifyNonce: false
    );
  }
```

I'm unsure if this is a correct behavior from my IAM, but in any case, maybe the bundle could allow passing the scopes as an optional argument for refreshTokens ?

Regards,
Grégoire

**Comment by bobvandevijver** [comment]
According to the [OAuth RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-6) (and nothing that contradicts this in the OpenID RFC), scopes are optional for the refresh request:

> The scope of the access request as described by [Section 3.3](https://datatracker.ietf.org/doc/html/rfc6749#section-3.3).  The requested scope MUST NOT include any scope not originally granted by the resource owner, and if omitted is treated as equal to the scope originally granted by the resource owner.

This does indeed mean that your IdP doesn't follow the specification correctly. Which provider are you using? You should let them know, so hopefully the can fix their implementation.

Having said that, the spec also supports using a narrower scope for the refresh, so I'm open for a PR that adds an optional parameter for the scopes.

**Comment by gregoire-jianda** [comment]
My provider is casdoor, and indeed their implementation doesn't account for this at all.
I opened an issue on their side and will try to push a PR too. I also pushed one here, since it could prove useful
