### ISSUE TITLE
Symfony 5.3 Authentication Manager

### ISSUE THREAD

**Issue by thewouter** [Drenso/symfony-oidc#8]
The 5.3 release of Symfony  has deprecated the previous security implementation in favour of the Authentication manager (https://symfony.com/doc/current/security/authenticator_manager.html). 

Updating to the Authentication manager with  Symfony-oidc as authentication provider gives an error message. This message mentions that oidc cannot be configured because it does not support the new authentication manager.

**Comment by bobvandevijver** [comment]
Unfortunately this bundle does not support the new authentication manager at this time and thus relies on the old, pre-guard interfaces for its functionality.

The current plan is to update to the new authentication manager once Symfony 5.4/6.0 are released. As this upgrade requires an almost complete rewrite, I cannot give an accurate estimate on when that will be finished though...

**Comment by bobvandevijver** [comment]
@thewouter Good news! I've just finished the first version of 2.x of this bundle. You can try it by requiring the dev version:

```
composer req drenso/symfony-oidc-bundle:dev-master
```

You will need to check the migration guide as a lot has changed, it is available here: https://github.com/Drenso/symfony-oidc/blob/master/UPGRADE.md. Note that the flex recipe is not available yet, it is currently pending review/merge: https://github.com/symfony/recipes-contrib/pull/1319.

I would love to hear your feedback on the migration!

**Comment by bobvandevijver** [comment]
V2 has been released, so I'm closing this one as resolved 🎉
